### ISSUE TITLE
Unable to fetch assets after Ember 2.7 upgrade

### ISSUE THREAD

**Issue by claire-lee** [ember-fastboot/fastboot-express-middleware#12]
After upgrading to Ember 2.7 (which included [deprecation of baseURL](http://emberjs.com/blog/2016/04/28/baseURL.html)) and starting an Ember app using Fastboot, the app tries to retrieve assets based on the rootURL specified, e.g. 
- rootURL/assets/vendor.css
- rootURL/assets/appName.js

However, Fastboot is still serving these assets at 
- assets/vendor.css
- assets/appName.js

**Comment by claire-lee** [comment]
Just wondering if anyone has had a chance to take a look at this.

**Comment by kfoisy** [comment]
I think this is actually a problem with the ember-cli-fastboot project. I've submitted a pull request to fix the issue there (see https://github.com/ember-fastboot/ember-cli-fastboot/pull/273).

**Comment by danmcclain** [comment]
We don't serve assets here, should be fixed in ember-cli-fastboot (aka @kfoisy's PR), and also fastboot-app-server needs to be updated. As the issue exists in those 2 repos
