### ISSUE TITLE
Can't get distPath when set value to resilient mode

### ISSUE THREAD

**Issue by tuanluu-agilityio** [ember-fastboot/fastboot-express-middleware#28]
Currently when we set value `resilient: true`, `fastboot-express-middleware` show `undefined` on `distPath` with code:
```
app.get('/*', fastbootMiddleware('/path/to/dist', {
  resilient: true
}));
```
Code above show `options` paramter on `constructor` in path file: `node_modules/fastboot/src/index.js`:
```
{distPath: undefined, resilient: true}
```

I have update it with code:
```
app.get('/*', fastbootMiddleware({
  distPath: '/path/to/dist',
  resilient: true
}));
```
Code above show `options` paramter on `constructor` in path file: `node_modules/fastboot/src/index.js`:
```
{distPath:  '/path/to/dist', resilient: true}
```
It work fine to me.

Please help check it again.

Thanks,

**Comment by kratiahuja** [comment]
fastboot-express-middleware only takes one parameter which either can be a `string` or `object`. `string` is used when you are _only_ passing path to dist. `object` is used when you want to pass the dist path and other parameters. In your case, you need to past `distPath` in the options parameter. When not using the resilient flag and just passing the dist it can either be set as `{distPath: 'path/to/dist'}` or pass it as a string.

**Comment by tuanluu-agilityio** [comment]
Hi @kratiahuja,

Thanks your reply, so should we update README file on section `Resilient Mode`? Because when I follow README file on section `Resilient Mode`, it not true and make me debug on source code to find issue.

Thanks,

**Comment by kratiahuja** [comment]
Sure please send a PR.

**Comment by tuanluu-agilityio** [comment]
Hi @kratiahuja,

I updated README file but currently I can't push it to `GH`. It show error:
```
remote: Permission to ember-fastboot/fastboot-express-middleware.git denied to tuanluu-agilityio.
fatal: unable to access 'https://github.com/ember-fastboot/fastboot-express-middleware.git/': The requested URL returned error: 403
```

Could you please help add me as Collaborators into this repo?

**Comment by kratiahuja** [comment]
Please fork the repo, create a branch, commit your changes and send a pull request: https://help.github.com/articles/fork-a-repo/ (then follow the instructions for sending a pull request here: https://help.github.com/articles/about-pull-requests/)
