### ISSUE TITLE
Release with FastBoot 2+ support

### ISSUE THREAD

**Issue by bobisjan** [ember-fastboot/fastboot-express-middleware#46]
Hi 👋,

the `fastboot` 2+ dependency is already included it the `package.json` 🎉.

Would it make sense to release a new version, so `ember-cli-fastboot` and `fastboot-app-server` can be updated too?

**Comment by lucacorti** [comment]
I submitted ember-fastboot/fastboot-app-server/pull/102 which solves a compatibility issue with `ember-data@3.9`, and `fastboot-express-middleware` also needs a release to remove the `fastboot` 1.x dependency.

**Comment by lucacorti** [comment]
@bobisjan 2.0.0 is released so I guess this can be closed.
