### ISSUE TITLE
Release v2.0.1?

### ISSUE THREAD

**Issue by bobisjan** [ember-fastboot/fastboot-express-middleware#71]
Hi 👋,

would it make sense to release a patch version with #60?

Thanks

/cc @rwjblue

**Comment by rwjblue** [comment]
It can't be a patch, since we also bumped node support. I was trying to land the FastBoot update but ran into some issues with a few of the resilient tests and ran out of time :(

**Comment by bobisjan** [comment]
I understand 🙌, but happy to help, assuming #70 is the PR with FastBoot update?

**Comment by rwjblue** [comment]
Ya, just haven't had any time more to dig into why those tests are failing. Help very much appreciated.

**Comment by rwjblue** [comment]
https://github.com/ember-fastboot/fastboot-express-middleware/releases/tag/v3.0.0

**Comment by bobisjan** [comment]
@rwjblue, excellent 🎉
